### PR TITLE
Fix: added SQL statement to create tables

### LINKED ISSUE #20: [FEATURE REQUEST]: SQL statement to create table Meetings and save in database/migrations
**Is your feature request related to a problem? Please describe.**
a feature of on the DB

**Describe the solution you'd like**
null.

**Describe alternatives you've considered**
null.

**Additional context**

DB Structure:
   Table: Meeting
   Fields:Id. event_id:int, employee_id: int, user_id:init,timestamps,
   Table:meeting_participant
   Fields: id, event_id: int, employee_id: init, user_id: init, timestamps,

DB Design Tasks:
 2. - Define SQL statement to create table Meetings and save in database/migrations.

### PR DESCRIPTION
**Pull request by delight500**
Resolve #20

### CODE REVIEW

**Review by horlathunbhosun — APPROVED** [review]

**Comment by horlathunbhosun** [comment]
@dave-ok  please check this db schema out

**Review by kay-ai — CHANGES_REQUESTED** [review]
Instead of editing already created migrations, it would be better creating new migrations, using;
`php artisan make:migration migration_name`
and
`php artisan migrate`

**Comment by delight500** [comment]
I created new migrations before when i wanted to pull it continued to give me errors so I re-cloned the project and deleted the users migrations and copied the former migrations to the directory that's why its showing like that

**Comment by horlathunbhosun** [comment]
please @delight500 make those fixes and create a new pull request

**Comment by delight500** [comment]
made the necessary changes @dave-ok @horlathunbhosun

**Pull request closed without merging**
